/**
 * Desktop liveness heartbeat for the in-game addon.
 *
 * Writes `SimlyHeartbeat.lua` (a sibling of SimlyResults.lua in the
 * SimlyResults addon folder) every `intervalMs` with a fresh
 * timestamp. The addon reads `_G.SimlyHeartbeat.alive_at` at
 * PLAYER_LOGIN; if it's missing OR stale by more than ~5 minutes
 * relative to wall-clock at login, the addon warns the user that the
 * desktop isn't running.
 *
 * Why a separate file and not just stamping SimlyResults: the results
 * file is large (~85KB once a real sim has populated it) and contention-
 * sensitive — the scan-queue writes it between stages, and a midstream
 * heartbeat write could race the queue's atomic temp-file-rename.
 * SimlyHeartbeat.lua is tiny and never read mid-session by anything
 * but the next /reload, so it's safe to overwrite freely.
 *
 * WoW only loads .lua files listed in the addon's .toc, so the toc
 * gets a second file entry. See `ensureHeartbeatToc` below.
 */

import { join } from 'node:path';
import { writeFile, rename } from 'node:fs/promises';
import { existsSync, readFileSync } from 'node:fs';

/** Interval is 60s by default — small enough to bound staleness, large
 * enough to be ~free in disk-write cost. */
export const DEFAULT_HEARTBEAT_INTERVAL_MS = 60_000;

/** Filename written into the SimlyResults addon folder. */
export const HEARTBEAT_FILENAME = 'SimlyHeartbeat.lua';

/**
 * The line that must appear in SimlyResults.toc for WoW to load the
 * heartbeat file. Idempotent — `ensureHeartbeatToc` adds it only if
 * missing.
 */
export const HEARTBEAT_TOC_LINE = 'SimlyHeartbeat.lua';

export interface HeartbeatHandle {
  /** Stop the interval and prevent further writes. Idempotent. */
  stop(): void;
  /** Resolves when the initial write completes. Useful in tests. */
  ready: Promise<void>;
}

/**
 * Pure helper: turn a heartbeat record into the Lua source the addon
 * will load. Exposed for tests so they don't need a tmp dir.
 */
export function formatHeartbeatLua(opts: {
  aliveAt: number;
  startedAt: number;
  version: string;
}): string {
  // Plain `SimlyHeartbeat = { ... }` global so the addon can read it
  // with `_G.SimlyHeartbeat`. No SavedVariables — it's static data
  // loaded from the addon folder at /reload.
  return [
    '-- Auto-generated by Simly desktop. Do not edit.',
    `SimlyHeartbeat = {`,
    `  alive_at = ${opts.aliveAt},`,
    `  started_at = ${opts.startedAt},`,
    `  version = ${JSON.stringify(opts.version)},`,
    `}`,
    '',
  ].join('\n');
}

/**
 * Start the heartbeat. Writes once immediately so the addon sees a
 * fresh value on the next /reload, then every `intervalMs` until
 * stopped.
 *
 * Writes go through a temp file + rename to make sure WoW never
 * reads a half-written .lua (same atomic pattern as the results
 * writer).
 *
 * The interval is unref'd so a stalled heartbeat doesn't hold the
 * Electron app open during quit.
 */
export function startHeartbeat(opts: {
  resultsAddonDir: string;
  version: string;
  intervalMs?: number;
}): HeartbeatHandle {
  const intervalMs = opts.intervalMs ?? DEFAULT_HEARTBEAT_INTERVAL_MS;
  const targetPath = join(opts.resultsAddonDir, HEARTBEAT_FILENAME);
  const startedAt = Math.floor(Date.now() / 1000);

  let stopped = false;
  const write = async (): Promise<void> => {
    if (stopped) return;
    const aliveAt = Math.floor(Date.now() / 1000);
    const lua = formatHeartbeatLua({ aliveAt, startedAt, version: opts.version });
    const tmpPath = `${targetPath}.tmp-${process.pid}-${aliveAt}`;
    try {
      await writeFile(tmpPath, lua, 'utf8');
      await rename(tmpPath, targetPath);
    } catch (err) {
      // Heartbeat write failure is non-fatal — at worst the addon
      // will warn "desktop not running" when it actually is. Don't
      // crash the app for this.
      console.warn(
        '[heartbeat] write failed:',
        (err as Error).message,
        '— continuing',
      );
    }
  };

  // Kick off an initial write so the addon sees a fresh value
  // immediately, even if the user /reloads before the first
  // interval fires.
  const ready = write();
  const timer = setInterval(() => void write(), intervalMs);
  // Don't keep the process alive just for the heartbeat.
  if (typeof timer.unref === 'function') timer.unref();

  return {
    stop(): void {
      stopped = true;
      clearInterval(timer);
    },
    ready,
  };
}

/**
 * Ensure SimlyResults.toc lists `SimlyHeartbeat.lua` so WoW actually
 * loads it. Reads the existing toc; if `SimlyHeartbeat.lua` isn't on
 * its own line, appends one.
 *
 * Returns true when the toc was modified (caller can log it).
 * Returns false when no change was needed or the toc didn't exist
 * (the caller is expected to write a fresh toc separately with both
 * files listed).
 */
export function ensureHeartbeatToc(tocPath: string): boolean {
  if (!existsSync(tocPath)) return false;
  const contents = readFileSync(tocPath, 'utf8');
  // Check for the bare line — defends against substrings like
  // "MySimlyHeartbeat.lua.bak".
  const lines = contents.split(/\r?\n/);
  if (lines.some((l) => l.trim() === HEARTBEAT_TOC_LINE)) return false;
  // Append. Preserve trailing newline so the file ends cleanly.
  const updated = contents.replace(/\s*$/, '') + '\n' + HEARTBEAT_TOC_LINE + '\n';
  try {
    // Synchronous: the caller is the boot path; we want this done
    // before the addon could possibly /reload and miss the file.
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    require('node:fs').writeFileSync(tocPath, updated, 'utf8');
    return true;
  } catch (err) {
    console.warn('[heartbeat] failed to update toc:', (err as Error).message);
    return false;
  }
}
